### ISSUE TITLE
publication for CAUSE

### ISSUE THREAD

**Issue by jean997** [workflowr/workflowr.io#1]
## 1. What is the [DOI][] of the publication?
https://doi.org/10.1038/s41588-020-0631-4

## 2. Which workflowr projects are associated with this publication?
jean997/cause

[DOI]: https://en.wikipedia.org/wiki/Digital_object_identifier

**Comment by jdblischak** [comment]
It's live: https://workflowr.io/publications/morrison2020/ Thanks!
