### ISSUE TITLE
BloomSail

### ISSUE THREAD

**Issue by jens-daniel-mueller** [workflowr/workflowr.io#2]
## 1. The [DOI] of the preprint, currently undergoing public discussion (review), is:
https://doi.org/10.5194/bg-2021-40

## 2. Which workflowr projects are associated with this publication?
https://workflowr.io/projects/github/jens-daniel-mueller/bloomsail/

**Comment by jdblischak** [comment]
Your publication is now live on the site: https://workflowr.io/publications/müller2021/

Thanks for your patience! I had to update multiple places to enable the raw HTML in your publication title to be properly rendered.

**Comment by jens-daniel-mueller** [comment]
Thanks John! Looks fantastic.
