### ISSUE TITLE
Adding rss-net to workflowr.io

### ISSUE THREAD

**Issue by xiangzhu** [workflowr/workflowr.io#3]
## 1. What is the [DOI][] of the publication?

https://doi.org/10.1038/s41467-021-22588-0

## 2. Which workflowr projects are associated with this publication?

https://github.com/SUwonglab/rss-net

[DOI]: https://en.wikipedia.org/wiki/Digital_object_identifier

**Comment by jdblischak** [comment]
Your project and publication are live! https://workflowr.io/publications/zhu2021/ 🎉
