### ISSUE TITLE
publication for QuRIE-seq_manuscript workflowr project

### ISSUE THREAD

**Issue by vanbuggenum** [workflowr/workflowr.io#4]
## 1. What is the [DOI][] of the publication?

https://doi.org/10.1016/j.crmeth.2021.100070

## 2. Which workflowr projects are associated with this publication?

https://github.com/vanbuggenum/QuRIE-seq_manuscript

[DOI]: https://en.wikipedia.org/wiki/Digital_object_identifier

**Comment by jdblischak** [comment]
@vanbuggenum Thanks for sharing your project and publication on workflowr.io! Your publication is live on the website now at https://workflowr.io/publications/rivello2021/
