### ISSUE TITLE
Add R-gene analysis preprint to workflowr project

### ISSUE THREAD

**Issue by philippbayer** [workflowr/workflowr.io#5]
## 1. What is the [DOI][] of the publication?

https://doi.org/10.1101/2021.12.12.472330

https://www.biorxiv.org/content/10.1101/2021.12.12.472330v1

## 2. Which workflowr projects are associated with this publication?

https://github.com/philippbayer/R_gene_analysis

Thank you!!

[DOI]: https://en.wikipedia.org/wiki/Digital_object_identifier

**Comment by jdblischak** [comment]
@philippbayer Thanks for sharing! https://workflowr.io/publications/bayer2021/
