### ISSUE TITLE
pre print associated with paed-cf-cite-seq project

### ISSUE THREAD

**Issue by JovMaksimovic** [workflowr/workflowr.io#7]
## 1. What is the [DOI][] of the publication?
https://doi.org/10.1101/2022.06.17.496207

## 2. Which workflowr projects are associated with this publication?
"GitHub - Oshlack/paed-cf-cite-seq" https://github.com/Oshlack/paed-cf-cite-seq

[DOI]: https://en.wikipedia.org/wiki/Digital_object_identifier

**Comment by jdblischak** [comment]
@JovMaksimovic Thanks for sharing! https://workflowr.io/publications/maksimovic2022/
