### ISSUE TITLE
publication associated with methyl-geneset-testing

### ISSUE THREAD

**Issue by JovMaksimovic** [workflowr/workflowr.io#8]
## 1. What is the [DOI][] of the publication?
https://doi.org/10.1186/s13059-021-02388-x

## 2. Which workflowr projects are associated with this publication?
"GitHub - Oshlack/methyl-geneset-testing" https://github.com/Oshlack/methyl-geneset-testing

[DOI]: https://en.wikipedia.org/wiki/Digital_object_identifier

**Comment by jdblischak** [comment]
@JovMaksimovic Thanks for sharing! https://workflowr.io/publications/maksimovic2021/
